//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apartman_Yonetimi_ms.Models_db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Apartman_yonetimi_msEntities : DbContext
    {
        public Apartman_yonetimi_msEntities()
            : base("name=Apartman_yonetimi_msEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apartman_islemleri> apartman_islemleri { get; set; }
        public virtual DbSet<borc_tipi> borc_tipi { get; set; }
        public virtual DbSet<borclar> borclars { get; set; }
        public virtual DbSet<daire> daires { get; set; }
        public virtual DbSet<gelirler> gelirlers { get; set; }
        public virtual DbSet<giderler> giderlers { get; set; }
        public virtual DbSet<kullanici> kullanicis { get; set; }
        public virtual DbSet<duyuru> duyurus1 { get; set; }
        public virtual DbSet<odenen> odenens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<yetki> yetkis { get; set; }
    }
}
