//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apartman_Yonetimi_ms.Models_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class odenen
    {
        public int id { get; set; }
        public string odeyen { get; set; }
        public Nullable<decimal> miktar { get; set; }
        public string odeme_turu { get; set; }
        public string odeme_onaylayan { get; set; }
    }
}
